//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumableData
    {
        public int ItemID { get; set; }
        public string ModifierType { get; set; }
        public int ModiferStat { get; set; }
    
        public virtual ConsumableTypeData ConsumableTypeData { get; set; }
        public virtual ItemData ItemData { get; set; }
    }
}
