//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreatureData
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public int CurrentHitPoints { get; set; }
        public int MaxHitPoints { get; set; }
        public int BaseArmor { get; set; }
        public int EquippedWeaponID { get; set; }
        public Nullable<int> Armor_HeadID { get; set; }
        public Nullable<int> Armor_ChestID { get; set; }
        public Nullable<int> Armor_LegsID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ItemData ItemData { get; set; }
        public virtual ItemData ItemData1 { get; set; }
        public virtual ItemData ItemData2 { get; set; }
        public virtual ItemData ItemData3 { get; set; }
    }
}
