//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemData()
        {
            this.CreatureDatas = new HashSet<CreatureData>();
            this.CreatureDatas1 = new HashSet<CreatureData>();
            this.CreatureDatas2 = new HashSet<CreatureData>();
            this.CreatureDatas3 = new HashSet<CreatureData>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    
        public virtual ArmorData ArmorData { get; set; }
        public virtual ConsumableData ConsumableData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreatureData> CreatureDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreatureData> CreatureDatas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreatureData> CreatureDatas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreatureData> CreatureDatas3 { get; set; }
        public virtual ItemTypeData ItemTypeData { get; set; }
        public virtual WeaponData WeaponData { get; set; }
    }
}
