//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RatatoskrContext : DbContext
    {
        public RatatoskrContext()
            : base("name=RatatoskrContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<ArmorData> ArmorDatas { get; set; }
        public virtual DbSet<ConsumableData> ConsumableDatas { get; set; }
        public virtual DbSet<ConsumableTypeData> ConsumableTypeDatas { get; set; }
        public virtual DbSet<CreatureData> CreatureDatas { get; set; }
        public virtual DbSet<EquipmentSlotData> EquipmentSlotDatas { get; set; }
        public virtual DbSet<ItemData> ItemDatas { get; set; }
        public virtual DbSet<ItemTypeData> ItemTypeDatas { get; set; }
        public virtual DbSet<WeaponData> WeaponDatas { get; set; }
    }
}
