//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Item()
        {
            this.Tbl_Creature = new HashSet<Tbl_Creature>();
            this.Tbl_Creature1 = new HashSet<Tbl_Creature>();
            this.Tbl_Creature2 = new HashSet<Tbl_Creature>();
            this.Tbl_Creature3 = new HashSet<Tbl_Creature>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    
        public virtual Tbl_Armor Tbl_Armor { get; set; }
        public virtual Tbl_Consumable Tbl_Consumable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Creature> Tbl_Creature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Creature> Tbl_Creature1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Creature> Tbl_Creature2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Creature> Tbl_Creature3 { get; set; }
        public virtual Tbl_ItemType Tbl_ItemType { get; set; }
        public virtual Tbl_Weapon Tbl_Weapon { get; set; }
    }
}
