//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Creature
    {
        public int UserId { get; set; }
        public string CharacterName { get; set; }
        public int CurrentHitPoints { get; set; }
        public int MaxHitPoints { get; set; }
        public string BaseDamage { get; set; }
        public int BaseArmor { get; set; }
        public int EquippedWeapon { get; set; }
        public Nullable<int> Armor_Head { get; set; }
        public Nullable<int> Armor_Chest { get; set; }
        public Nullable<int> Armor_Legs { get; set; }
    
        public virtual Tbl_Account Tbl_Account { get; set; }
        public virtual Tbl_Item Tbl_Item { get; set; }
        public virtual Tbl_Item Tbl_Item1 { get; set; }
        public virtual Tbl_Item Tbl_Item2 { get; set; }
        public virtual Tbl_Item Tbl_Item3 { get; set; }
    }
}
