//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponData
    {
        public int ItemID { get; set; }
        public string EquipmentSlot { get; set; }
        public string DamageDice { get; set; }
    
        public virtual EquipmentSlotData EquipmentSlotData { get; set; }
        public virtual ItemData ItemData { get; set; }
    }
}
